openapi: 3.0.0
info:
  title: Coin-tracker API
  version: 1.0.0
  description: API to manage a cryptocurrency watchlist
paths:
  /watchlist:
    post:
      summary: Add coin to watchlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Coin'
      responses:
        '201':
          description: Coin added to watchlist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coin'
        '400':
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to add coin to watchlist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get watchlist
      responses:
        '200':
          description: Watchlist retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Coin'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to retrieve watchlist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /watchlist/{symbol}:
    delete:
      summary: Remove coin from watchlist
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
            example: BTC
          description: The symbol of the cryptocurrency to be removed
      responses:
        '200':
          description: Coin removed from watchlist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '400':
          description: Bad Request - Invalid symbol
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to remove coin from watchlist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Coin:
      type: object
      properties:
        symbol:
          type: string
          description: The symbol of the cryptocurrency
          example: BTC
        name:
          type: string
          description: The name of the cryptocurrency
          example: Bitcoin
        image:
          type: string
          description: URL of the cryptocurrency image
          example: https://example.com/bitcoin.png
        price_change_percentage_24h:
          type: number
          description: The 24-hour price change percentage of the cryptocurrency
          example: 2.5
        current_price:
          type: number
          description: The current price of the cryptocurrency
          example: 50000
        total_volume:
          type: number
          description: The total volume of the cryptocurrency
          example: 3500000000
        market_cap:
          type: number
          description: The market capitalization of the cryptocurrency
          example: 900000000000
      required:
        - symbol
        - name
        - price_change_percentage_24h
        - current_price
        - total_volume
        - market_cap
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "Invalid input data"
    Success:
      type: object
      properties:
        message:
          type: string
          description: Success message
          example: "Coin removed from watchlist"