openapi: 3.0.0
info:
  title: Notification API
  version: "1.0.0"
  description: A RESTful API with resource-based URIs and proper use of HTTP methods for managing notifications.

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

paths:
  /notifications:
    get:
      summary: Retrieve all notifications
      description: Get a complete list of all notifications stored.
      responses:
        "200":
          description: List of notifications returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notification"
        "500":
          description: Error occurred while retrieving notifications
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      summary: Create a new notification
      description: Add a new notification entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewNotification"
      responses:
        "201":
          description: Notification created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notification"
        "400":
          description: Bad request, invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /notifications/{userId}:
    get:
      summary: Retrieve notifications for a specific user
      description: List all notifications for the given user ID.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: Unique identifier for the user.
      responses:
        "200":
          description: Notifications fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notification"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error during request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      summary: Remove all notifications for a user
      description: Deletes every notification tied to the specified user ID.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user whose notifications will be deleted.
      responses:
        "204":
          description: Notifications deleted successfully, no content returned
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server issue
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /notifications/{notifId}:
    get:
      summary: Retrieve a specific notification
      description: Get a specific notification by its unique ID.
      parameters:
        - in: path
          name: notifId
          required: true
          schema:
            type: string
          description: The unique identifier of the notification.
      responses:
        "200":
          description: Notification retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notification"
        "404":
          description: Notification not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Notification:
      type: object
      properties:
        notifId:
          type: string
          description: Unique identifier for the notification.
        message:
          type: string
          description: The content of the notification.
        timestamp:
          type: string
          format: date-time
          description: The time when the notification was created.
        userId:
          type: string
          description: The ID of the user associated with the notification.
      required:
        - notifId
        - message
        - timestamp
        - userId

    NewNotification:
      type: object
      properties:
        message:
          type: string
          description: The content of the new notification.
        userId:
          type: string
          description: The ID of the user for whom the notification is created.
      required:
        - message
        - userId

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: The HTTP status code of the error.
        message:
          type: string
          description: A detailed error message.
      required:
        - code
        - message
