openapi: 3.0.0
info:
  title: Blog API
  version: 1.0.0
  description: >-
    API for managing blogs, including creating, updating, retrieving, and
    deleting blog posts.
paths:
  /blogs:
    get:
      summary: Retrieve all blogs
      responses:
        '200':
          description: List of all blogs retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'
        '500':
          description: Internal server error while retrieving blogs
    post:
      summary: Create a new blog post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogCreate'
      responses:
        '201':
          description: Blog created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '400':
          description: Bad request due to invalid blog data
        '500':
          description: Internal server error while creating the blog
  /blogs/{blogId}:
    get:
      summary: Get a specific blog by ID
      parameters:
        - name: blogId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Blog retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '404':
          description: Blog not found
        '500':
          description: Internal server error while retrieving blog
    put:
      summary: Update an existing blog post
      parameters:
        - name: blogId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogUpdate'
      responses:
        '200':
          description: Blog updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '400':
          description: Bad request due to invalid data
        '404':
          description: Blog not found
        '500':
          description: Internal server error while updating blog
    delete:
      summary: Delete a blog post
      parameters:
        - name: blogId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Blog deleted successfully
        '404':
          description: Blog not found
        '500':
          description: Internal server error while deleting blog
  /blogs/author/{userId}:
    get:
      summary: Get all blogs authored by a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Blogs authored by the user retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'
        '404':
          description: No blogs found for the specified author
        '500':
          description: Internal server error while retrieving blogs
components:
  schemas:
    Blog:
      type: object
      properties:
        blogId:
          type: string
          description: Unique identifier for the blog
        title:
          type: string
          description: Title of the blog
        content:
          type: string
          description: Content of the blog
        authorId:
          type: string
          description: ID of the user who authored the blog
      required:
        - blogId
        - title
        - content
        - authorId
    BlogCreate:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        authorId:
          type: string
      required:
        - title
        - content
        - authorId
    BlogUpdate:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content
