openapi: 3.0.0
info:
  title: Portfolio API
  version: 1.0.0
  description: >-
    API for managing user portfolios, including retrieving and updating coin
    details and total value.
paths:
  /portfolio/{userId}:
    get:
      summary: Retrieve the user's portfolio with coin details and total value
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >-
            User's portfolio retrieved successfully with coin details and total
            value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Portfolio'
        '400':
          description: Bad request due to invalid user ID
        '401':
          description: Unauthorized access - user authentication required
        '403':
          description: Forbidden - user does not have permission to access this portfolio
        '404':
          description: Portfolio not found for the specified user
        '500':
          description: Internal server error while retrieving portfolio
    put:
      summary: Update the user's portfolio (e.g., adding or removing coins)
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PortfolioUpdate'
      responses:
        '200':
          description: Portfolio updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Portfolio'
        '400':
          description: Bad request due to invalid data format or missing fields
        '401':
          description: Unauthorized access - user authentication required
        '403':
          description: Forbidden - user does not have permission to update this portfolio
        '404':
          description: Portfolio not found for the specified user
        '409':
          description: Conflict - specified coins already exist in the portfolio
        '500':
          description: Internal server error while updating the portfolio
components:
  schemas:
    Portfolio:
      type: object
      properties:
        userId:
          type: string
          format: uuid
          description: Unique identifier for the user
        coins:
          type: array
          description: List of coins in the user's portfolio
          items:
            $ref: '#/components/schemas/Coin'
        totalValue:
          type: number
          format: decimal
          description: Total value of all coins in the portfolio
      required:
        - userId
        - coins
        - totalValue
    PortfolioUpdate:
      type: object
      properties:
        coins:
          type: array
          description: List of coins to add or update in the portfolio
          items:
            $ref: '#/components/schemas/Coin'
        removeCoins:
          type: array
          description: List of coin symbols to remove from the portfolio
          items:
            type: string
            description: Symbol of the coin to be removed
      required:
        - coins
    Coin:
      type: object
      properties:
        coinId:
          type: string
          format: uuid
          description: Unique identifier for the coin
        symbol:
          type: string
          description: Symbol representing the coin
        value:
          type: number
          format: decimal
          description: Value of the coin
        quantity:
          type: number
          format: decimal
          description: Quantity of the coin in the portfolio
      required:
        - coinId
        - symbol
        - value
        - quantity
