openapi: 3.0.0
info:
  title: Market Trends API
  version: "1.0.0"
  description: A RESTful API for managing market trend data and analytics.

servers:
  - url: https://api.markettrends.com/v1
    description: Production server
  - url: https://staging-api.markettrends.com/v1
    description: Staging server

paths:
  /trends:
    get:
      summary: Retrieve all market trends
      description: Get a complete list of all market trends with trend details.
      responses:
        "200":
          description: List of market trends returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MarketTrend"
        "400":
          description: Bad request, invalid parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Error occurred while retrieving market trends
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    post:
      summary: Create a new market trend
      description: Add a new market trend entry with trend data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewMarketTrend"
      responses:
        "201":
          description: Market trend created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarketTrend"
        "400":
          description: Bad request, invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /market-trends/today:
    get:
      summary: Get today's market trends
      description: Retrieve today's market trends, including price changes and statistics for coins.
      responses:
        "200":
          description: Today's market trends returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MarketTrend"
        "400":
          description: Bad request, invalid parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /market-trends/{coinId}:
    get:
      summary: Get market trend details for a specific coin
      description: Retrieve the market trend details for a specific coin by its ID.
      parameters:
        - in: path
          name: coinId
          required: true
          schema:
            type: string
          description: The unique identifier for the coin.
      responses:
        "200":
          description: Market trend details for the coin returned successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarketTrend"
        "400":
          description: Bad request, invalid parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Coin not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /market-trends/{userId}:
    get:
      summary: Get user's preferred market trends or coin stats
      description: Retrieve the user's preferred market trends or specific coin statistics by user ID.
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: The unique identifier for the user.
      responses:
        "200":
          description: User's preferred market trends or coin stats returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MarketTrend"
        "400":
          description: Bad request, invalid parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: User not found or no preferences available
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    MarketTrend:
      type: object
      properties:
        trendId:
          type: string
          description: Unique identifier for the market trend.
        name:
          type: string
          description: The name or title of the market trend.
        description:
          type: string
          description: A detailed description of the market trend.
        date:
          type: string
          format: date-time
          description: The date when the trend was recorded or last updated.
        category:
          type: string
          description: The category or sector of the market the trend is related to.
        value:
          type: number
          format: float
          description: The numerical value representing the strength or magnitude of the trend.
      required:
        - trendId
